//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeto_estoque_drogavida
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class operador
    {
        [Required]
        [Display(Name = "Nome")]
        public string nome { get; set; }
        [Display(Name = "CPF")]
        [Required(ErrorMessage = "Informe o nome do usuário", AllowEmptyStrings = false)]
        public string cpf_o { get; set; }
        [Display(Name = "Email")]
        [Required]
        public string email { get; set; }
        [Display(Name = "Senha")]
        [Required(ErrorMessage = "Informe a senha do usuário", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string senha { get; set; }
        [Required]
        [Display(Name = "Telefone")]
        public string tel { get; set; }
        [Required]
        [Display(Name = "Endereço")]
        public string endereco { get; set; }
        [Display(Name = "Data de nascimento")]
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        public string data_de_nascimento { get; set; }
    }
}
