//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogaria_DrogaVida
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdutoModel : DbContext
    {
        public ProdutoModel()
            : base("name=ProdutoModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<operador> operador { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<receita> receita { get; set; }
    }
}
