//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogaria_DrogaVida
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int Id_produto { get; set; }
        public string nome { get; set; }
        public string cod_barra { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public string marca { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> qda_estoque { get; set; }
        public byte[] imagem { get; set; }
        public Nullable<double> valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
