//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogaria_DrogaVida
{
    using System;
    using System.Collections.Generic;
    
    public partial class receita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receita()
        {
            this.pedido1 = new HashSet<pedido>();
        }
    
        public int Id_aprovacao { get; set; }
        public Nullable<bool> status_receita { get; set; }
        public byte[] receita1 { get; set; }
        public string cpf_o { get; set; }
        public Nullable<int> Id_pedido { get; set; }
    
        public virtual operador operador { get; set; }
        public virtual pedido pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido1 { get; set; }
    }
}
